model: &model
  name: resnet18
  pretrained: False
  freeze: False
  num_classes: 1
  checkpoint_path: ''

train: &train
  num_epochs: 100

  optimizer: &optimizer
    name: sgd
    lr: 0.001
    weight_decay: 0.0

  criterion: &criterion
    name: cross_entropy

eval: &eval
  use_roc: True

data: &data
  name: wildcam
  root_dir: '/mnt/nfs/work1/ds4cg'
  batch_size: 128
  num_workers: 4
  label_type: binary

