model: &model
  name: resnet18
  pretrained: False
  freeze: False
  num_classes: 1
  checkpoint_path: ''
  # checkpoint_path: 'checkpoints/resnet18/resnet18_no_norm.pth'

train: &train
  num_epochs: 100
  save_dir: 'checkpoints/resnet18'

  optimizer: &optimizer
    name: sgd
    lr: 0.001
    weight_decay: 0.0

  criterion: &criterion
    name: cross_entropy

eval: &eval
  use_roc: False

data: &data
  name: wildcam
  root_dir: 'data'
  batch_size: 8
  num_workers: 1
  label_type: binary

