model: &model
  name: resnet18
  num_classes: 1

train: &train
  data: wildcam
  num_epochs: 100
  checkpoint_path: 'checkpoints/resnet18_test/resnet18_0.pth'

  optimizer: &optimizer
    name: sgd
    lr: 0.001
        weight_decay: 0.0

  lr_schedule: &lr_schedule
    step_size: 5
    gamma: 0.1

  criterion: &criterion
    gamma: 0
    # alpha: 0.5

eval: &eval
  data: wildcam
  use_roc: False
  checkpoint_path: 'checkpoints/resnet18_test'

data: &data
  root_dir: 'data'
  batch_size: 16
  num_workers: 1
  label_type: binary

