model: &model
  name: resnet18
  pretrained: False
  freeze: False
  num_classes: 2
  checkpoint_path: ''

train: &train
  num_epochs: 100

  optimizer: &optimizer
    name: sgd
    lr: 0.001
    weight_decay: 0.0

  criterion: &criterion
    name: cross_entropy


eval: &eval

data: &data

