model: &model
  name: vgg16
  num_classes: 1

train: &train
  data: wildcam
  num_epochs: 100
  checkpoint_path: '' # '' if training from scratch

  optimizer: &optimizer
    name: rmsprop
    lr: 0.00001
    alpha: 0.99
    eps: 0.0000001
    weight_decay: 0.0

  lr_schedule: &lr_schedule
    step_size: 3
    gamma: 0.1

  criterion: &criterion
    gamma: 1
    # alpha: 0.5

eval: &eval
  data: wildcam
  use_roc: False
  checkpoint_path: 'checkpoints/vgg16_no_illumination/checkpoint_best.pth' # either checkpoint dir or path

data: &data
  root_dir: '/mnt/nfs/work1/ds4cg/'
  batch_size: 128
  num_workers: 1
  label_type: binary

