model: &model
  name: vgg16
  num_classes: 1

train: &train
  data: wildcam
  num_epochs: 100
  checkpoint_path: 'checkpoints/vgg16_test/checkpoint_0.pth'

  optimizer: &optimizer
    name: rmsprop
    lr: 0.001
    alpha: 0.99
    eps: 0.000001
    weight_decay: 0.0

  lr_schedule: &lr_schedule
    step_size: 5
    gamma: 0.1

  criterion: &criterion
    name: cross_entropy

eval: &eval
  data: wildcam
  use_roc: False
  checkpoint_path: 'checkpoints/vgg16_test' # either checkpoint dir or path

data: &data
  root_dir: 'data'
  batch_size: 16
  num_workers: 1
  label_type: binary

